name: Run Nala Manually

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags, if empty all tests will run. i.e., @marquee'
        required: false
        type: string
      platform:
        description: 'Platform to run tests on; select one, options: [ubuntu-latest, windows-latest, macos-latest]'
        required: true
        type: string

jobs:
  action:
    name: Running tests
    runs-on: ${{ inputs.platform }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set permissions
        run: chmod +x ./run.sh
      - name: Run Nala ${{ inputs.platform }}
        uses: ./
        env:
          labels: ${{ inputs.tags }}
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
      - name: Save Results
        run: |

          reponame=${{ github.repository_owner }}
          branchname="${{ github.head_ref }}"
          timestamp=$(date '+%Y%m%d_%H%M%S')
          filename="test-results_${reponame}${branchname}_run.json"
          mv nala-results.json $filename
          #Display the constructed filename
          echo "Generated Filename: $filename"
          shell: bash
